# Acpi51.py
#
# EfiPy2.MdePkg.IndustryStandard.Acpi51
#   part of EfiPy, EfiPy2
#
# Copyright (C) 2015 - 2023 MaxWu efipy.core@gmail.com
#   GPL-2.0
#
from EfiPy2.MdePkg.IndustryStandard.Acpi50 import *

EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE = EFI_ACPI_5_0_GENERIC_ADDRESS_STRUCTURE

EFI_ACPI_5_1_SYSTEM_MEMORY              = 0
EFI_ACPI_5_1_SYSTEM_IO                  = 1
EFI_ACPI_5_1_PCI_CONFIGURATION_SPACE    = 2
EFI_ACPI_5_1_EMBEDDED_CONTROLLER        = 3
EFI_ACPI_5_1_SMBUS                      = 4
EFI_ACPI_5_1_PLATFORM_COMMUNICATION_CHANNEL  = 0x0A
EFI_ACPI_5_1_FUNCTIONAL_FIXED_HARDWARE       = 0x7F

EFI_ACPI_5_1_UNDEFINED  = 0
EFI_ACPI_5_1_BYTE       = 1
EFI_ACPI_5_1_WORD       = 2
EFI_ACPI_5_1_DWORD      = 3
EFI_ACPI_5_1_QWORD      = 4

EFI_ACPI_5_1_ROOT_SYSTEM_DESCRIPTION_POINTER = EFI_ACPI_5_0_ROOT_SYSTEM_DESCRIPTION_POINTER

EFI_ACPI_5_1_ROOT_SYSTEM_DESCRIPTION_POINTER_REVISION = 0x02

EFI_ACPI_5_1_COMMON_HEADER = EFI_ACPI_5_0_COMMON_HEADER

EFI_ACPI_5_1_ROOT_SYSTEM_DESCRIPTION_TABLE_REVISION = 0x01

EFI_ACPI_5_1_EXTENDED_SYSTEM_DESCRIPTION_TABLE_REVISION = 0x01

class EFI_ACPI_5_1_FIXED_ACPI_DESCRIPTION_TABLE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("Header",              EFI_ACPI_DESCRIPTION_HEADER),
    ("FirmwareCtrl",        UINT32),
    ("Dsdt",                UINT32),
    ("Reserved0",           UINT8),
    ("PreferredPmProfile",  UINT8),
    ("SciInt",              UINT16),
    ("SmiCmd",              UINT32),
    ("AcpiEnable",          UINT8),
    ("AcpiDisable",         UINT8),
    ("S4BiosReq",           UINT8),
    ("PstateCnt",           UINT8),
    ("Pm1aEvtBlk",          UINT32),
    ("Pm1bEvtBlk",          UINT32),
    ("Pm1aCntBlk",          UINT32),
    ("Pm1bCntBlk",          UINT32),
    ("Pm2CntBlk",           UINT32),
    ("PmTmrBlk",            UINT32),
    ("Gpe0Blk",             UINT32),
    ("Gpe1Blk",             UINT32),
    ("Pm1EvtLen",           UINT8),
    ("Pm1CntLen",           UINT8),
    ("Pm2CntLen",           UINT8),
    ("PmTmrLen",            UINT8),
    ("Gpe0BlkLen",          UINT8),
    ("Gpe1BlkLen",          UINT8),
    ("Gpe1Base",            UINT8),
    ("CstCnt",              UINT8),
    ("PLvl2Lat",            UINT16),
    ("PLvl3Lat",            UINT16),
    ("FlushSize",           UINT16),
    ("FlushStride",         UINT16),
    ("DutyOffset",          UINT8),
    ("DutyWidth",           UINT8),
    ("DayAlrm",             UINT8),
    ("MonAlrm",             UINT8),
    ("Century",             UINT8),
    ("IaPcBootArch",        UINT16),
    ("Reserved1",           UINT8),
    ("Flags",               UINT32),
    ("ResetReg",            EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("ResetValue",          UINT8),
    ("ArmBootArch",         UINT16),
    ("MinorVersion",        UINT8),
    ("XFirmwareCtrl",       UINT64),
    ("XDsdt",               UINT64),
    ("XPm1aEvtBlk",         EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("XPm1bEvtBlk",         EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("XPm1aCntBlk",         EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("XPm1bCntBlk",         EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("XPm2CntBlk",          EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("XPmTmrBlk",           EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("XGpe0Blk",            EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("XGpe1Blk",            EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("SleepControlReg",     EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("SleepStatusReg",      EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE)
  ]

EFI_ACPI_5_1_FIXED_ACPI_DESCRIPTION_TABLE_REVISION  = 0x05
EFI_ACPI_5_1_FIXED_ACPI_DESCRIPTION_TABLE_MINOR_REVISION  = 0x01

EFI_ACPI_5_1_PM_PROFILE_UNSPECIFIED         = 0
EFI_ACPI_5_1_PM_PROFILE_DESKTOP             = 1
EFI_ACPI_5_1_PM_PROFILE_MOBILE              = 2
EFI_ACPI_5_1_PM_PROFILE_WORKSTATION         = 3
EFI_ACPI_5_1_PM_PROFILE_ENTERPRISE_SERVER   = 4
EFI_ACPI_5_1_PM_PROFILE_SOHO_SERVER         = 5
EFI_ACPI_5_1_PM_PROFILE_APPLIANCE_PC        = 6
EFI_ACPI_5_1_PM_PROFILE_PERFORMANCE_SERVER  = 7
EFI_ACPI_5_1_PM_PROFILE_TABLET              = 8

EFI_ACPI_5_1_LEGACY_DEVICES              = BIT0
EFI_ACPI_5_1_8042                        = BIT1
EFI_ACPI_5_1_VGA_NOT_PRESENT             = BIT2
EFI_ACPI_5_1_MSI_NOT_SUPPORTED           = BIT3
EFI_ACPI_5_1_PCIE_ASPM_CONTROLS          = BIT4
EFI_ACPI_5_1_CMOS_RTC_NOT_PRESENT        = BIT5

EFI_ACPI_5_1_ARM_PSCI_COMPLIANT              = BIT0
EFI_ACPI_5_1_ARM_PSCI_USE_HVC                = BIT1

EFI_ACPI_5_1_WBINVD                                 = BIT0
EFI_ACPI_5_1_WBINVD_FLUSH                           = BIT1
EFI_ACPI_5_1_PROC_C1                                = BIT2
EFI_ACPI_5_1_P_LVL2_UP                              = BIT3
EFI_ACPI_5_1_PWR_BUTTON                             = BIT4
EFI_ACPI_5_1_SLP_BUTTON                             = BIT5
EFI_ACPI_5_1_FIX_RTC                                = BIT6
EFI_ACPI_5_1_RTC_S4                                 = BIT7
EFI_ACPI_5_1_TMR_VAL_EXT                            = BIT8
EFI_ACPI_5_1_DCK_CAP                                = BIT9
EFI_ACPI_5_1_RESET_REG_SUP                          = BIT10
EFI_ACPI_5_1_SEALED_CASE                            = BIT11
EFI_ACPI_5_1_HEADLESS                               = BIT12
EFI_ACPI_5_1_CPU_SW_SLP                             = BIT13
EFI_ACPI_5_1_PCI_EXP_WAK                            = BIT14
EFI_ACPI_5_1_USE_PLATFORM_CLOCK                     = BIT15
EFI_ACPI_5_1_S4_RTC_STS_VALID                       = BIT16
EFI_ACPI_5_1_REMOTE_POWER_ON_CAPABLE                = BIT17
EFI_ACPI_5_1_FORCE_APIC_CLUSTER_MODEL               = BIT18
EFI_ACPI_5_1_FORCE_APIC_PHYSICAL_DESTINATION_MODE   = BIT19
EFI_ACPI_5_1_HW_REDUCED_ACPI                        = BIT20
EFI_ACPI_5_1_LOW_POWER_S0_IDLE_CAPABLE              = BIT21

EFI_ACPI_5_1_FIRMWARE_ACPI_CONTROL_STRUCTURE = EFI_ACPI_5_0_FIRMWARE_ACPI_CONTROL_STRUCTURE

EFI_ACPI_5_1_FIRMWARE_ACPI_CONTROL_STRUCTURE_VERSION  = 0x02

EFI_ACPI_5_1_S4BIOS_F                     = BIT0
EFI_ACPI_5_1_64BIT_WAKE_SUPPORTED_F       = BIT1

EFI_ACPI_5_1_OSPM_64BIT_WAKE_F            = BIT0

EFI_ACPI_5_1_DIFFERENTIATED_SYSTEM_DESCRIPTION_TABLE_REVISION   = 0x02
EFI_ACPI_5_1_SECONDARY_SYSTEM_DESCRIPTION_TABLE_REVISION        = 0x02

EFI_ACPI_5_1_MULTIPLE_APIC_DESCRIPTION_TABLE_HEADER = EFI_ACPI_5_0_MULTIPLE_APIC_DESCRIPTION_TABLE_HEADER

EFI_ACPI_5_1_MULTIPLE_APIC_DESCRIPTION_TABLE_REVISION = 0x03

EFI_ACPI_5_1_PCAT_COMPAT         = BIT0

EFI_ACPI_5_1_PROCESSOR_LOCAL_APIC           = 0x00
EFI_ACPI_5_1_IO_APIC                        = 0x01
EFI_ACPI_5_1_INTERRUPT_SOURCE_OVERRIDE      = 0x02
EFI_ACPI_5_1_NON_MASKABLE_INTERRUPT_SOURCE  = 0x03
EFI_ACPI_5_1_LOCAL_APIC_NMI                 = 0x04
EFI_ACPI_5_1_LOCAL_APIC_ADDRESS_OVERRIDE    = 0x05
EFI_ACPI_5_1_IO_SAPIC                       = 0x06
EFI_ACPI_5_1_LOCAL_SAPIC                    = 0x07
EFI_ACPI_5_1_PLATFORM_INTERRUPT_SOURCES     = 0x08
EFI_ACPI_5_1_PROCESSOR_LOCAL_X2APIC         = 0x09
EFI_ACPI_5_1_LOCAL_X2APIC_NMI               = 0x0A
EFI_ACPI_5_1_GIC                            = 0x0B
EFI_ACPI_5_1_GICD                           = 0x0C
EFI_ACPI_5_1_GIC_MSI_FRAME                  = 0x0D
EFI_ACPI_5_1_GICR                           = 0x0E

EFI_ACPI_5_1_PROCESSOR_LOCAL_APIC_STRUCTURE = EFI_ACPI_5_0_PROCESSOR_LOCAL_APIC_STRUCTURE

EFI_ACPI_5_1_LOCAL_APIC_ENABLED        = BIT0

EFI_ACPI_5_1_IO_APIC_STRUCTURE = EFI_ACPI_5_0_IO_APIC_STRUCTURE

EFI_ACPI_5_1_INTERRUPT_SOURCE_OVERRIDE_STRUCTURE = EFI_ACPI_5_0_INTERRUPT_SOURCE_OVERRIDE_STRUCTURE

EFI_ACPI_5_1_PLATFORM_INTERRUPT_APIC_STRUCTURE = EFI_ACPI_5_0_PLATFORM_INTERRUPT_APIC_STRUCTURE

EFI_ACPI_5_1_POLARITY      = (3 << 0)
EFI_ACPI_5_1_TRIGGER_MODE  = (3 << 2)

EFI_ACPI_5_1_NON_MASKABLE_INTERRUPT_SOURCE_STRUCTURE = EFI_ACPI_5_0_NON_MASKABLE_INTERRUPT_SOURCE_STRUCTURE

EFI_ACPI_5_1_LOCAL_APIC_NMI_STRUCTURE = EFI_ACPI_5_0_LOCAL_APIC_NMI_STRUCTURE

EFI_ACPI_5_1_LOCAL_APIC_ADDRESS_OVERRIDE_STRUCTURE = EFI_ACPI_5_0_LOCAL_APIC_ADDRESS_OVERRIDE_STRUCTURE

EFI_ACPI_5_1_IO_SAPIC_STRUCTURE = EFI_ACPI_5_0_IO_SAPIC_STRUCTURE

EFI_ACPI_5_1_PROCESSOR_LOCAL_SAPIC_STRUCTURE = EFI_ACPI_5_0_PROCESSOR_LOCAL_SAPIC_STRUCTURE

EFI_ACPI_5_1_PLATFORM_INTERRUPT_SOURCES_STRUCTURE = EFI_ACPI_5_0_PLATFORM_INTERRUPT_SOURCES_STRUCTURE

EFI_ACPI_5_1_CPEI_PROCESSOR_OVERRIDE          = BIT0

EFI_ACPI_5_1_PROCESSOR_LOCAL_X2APIC_STRUCTURE = EFI_ACPI_5_0_PROCESSOR_LOCAL_X2APIC_STRUCTURE

EFI_ACPI_5_1_LOCAL_X2APIC_NMI_STRUCTURE = EFI_ACPI_5_0_LOCAL_X2APIC_NMI_STRUCTURE

class EFI_ACPI_5_1_GIC_STRUCTURE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("Type",                      UINT8),
    ("Length",                    UINT8),
    ("Reserved",                  UINT16),
    ("CPUInterfaceNumber",        UINT32),
    ("AcpiProcessorUid",          UINT32),
    ("Flags",                     UINT32),
    ("ParkingProtocolVersion",    UINT32),
    ("PerformanceInterruptGsiv",  UINT32),
    ("ParkedAddress",             UINT64),
    ("PhysicalBaseAddress",       UINT64),
    ("GICV",                      UINT64),
    ("GICH",                      UINT64),
    ("VGICMaintenanceInterrupt",  UINT32),
    ("GICRBaseAddress",           UINT64),
    ("MPIDR",                     UINT64)
  ]

EFI_ACPI_5_1_GIC_ENABLED                              = BIT0
EFI_ACPI_5_1_PERFORMANCE_INTERRUPT_MODEL              = BIT1
EFI_ACPI_5_1_VGIC_MAINTENANCE_INTERRUPT_MODE_FLAGS    = BIT2

EFI_ACPI_5_1_GIC_DISTRIBUTOR_STRUCTURE = EFI_ACPI_5_0_GIC_DISTRIBUTOR_STRUCTURE

class EFI_ACPI_5_1_GIC_MSI_FRAME_STRUCTURE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("Type",                UINT8),
    ("Length",              UINT8),
    ("Reserved1",           UINT16),
    ("GicMsiFrameId",       UINT32),
    ("PhysicalBaseAddress", UINT64),
    ("Flags",               UINT32),
    ("SPICount",            UINT16),
    ("SPIBase",             UINT16)
  ]

EFI_ACPI_5_1_SPI_COUNT_BASE_SELECT                    = BIT0

class EFI_ACPI_5_1_GICR_STRUCTURE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("Type",                      UINT8),
    ("Length",                    UINT8),
    ("Reserved",                  UINT16),
    ("DiscoveryRangeBaseAddress", UINT64),
    ("DiscoveryRangeLength",      UINT32)
  ]

EFI_ACPI_5_1_SMART_BATTERY_DESCRIPTION_TABLE = EFI_ACPI_5_0_SMART_BATTERY_DESCRIPTION_TABLE

EFI_ACPI_5_1_SMART_BATTERY_DESCRIPTION_TABLE_REVISION = 0x01

class EFI_ACPI_5_1_EMBEDDED_CONTROLLER_BOOT_RESOURCES_TABLE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("Header",    EFI_ACPI_DESCRIPTION_HEADER),
    ("EcControl", EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("EcData",    EFI_ACPI_5_1_GENERIC_ADDRESS_STRUCTURE),
    ("Uid",       UINT32),
    ("GpeBit",    UINT8)
  ]

EFI_ACPI_5_1_EMBEDDED_CONTROLLER_BOOT_RESOURCES_TABLE_REVISION  = EFI_ACPI_5_0_EMBEDDED_CONTROLLER_BOOT_RESOURCES_TABLE_REVISION

EFI_ACPI_5_1_SYSTEM_RESOURCE_AFFINITY_TABLE_HEADER = EFI_ACPI_5_0_SYSTEM_RESOURCE_AFFINITY_TABLE_HEADER

EFI_ACPI_5_1_SYSTEM_RESOURCE_AFFINITY_TABLE_REVISION  = 0x03

EFI_ACPI_5_1_PROCESSOR_LOCAL_APIC_SAPIC_AFFINITY  = 0x00
EFI_ACPI_5_1_MEMORY_AFFINITY                      = 0x01
EFI_ACPI_5_1_PROCESSOR_LOCAL_X2APIC_AFFINITY      = 0x02
EFI_ACPI_5_1_GICC_AFFINITY                        = 0x03

EFI_ACPI_5_1_PROCESSOR_LOCAL_APIC_SAPIC_AFFINITY_STRUCTURE = EFI_ACPI_5_0_PROCESSOR_LOCAL_APIC_SAPIC_AFFINITY_STRUCTURE

EFI_ACPI_5_1_PROCESSOR_LOCAL_APIC_SAPIC_ENABLED = (1 << 0)

EFI_ACPI_5_1_MEMORY_AFFINITY_STRUCTURE = EFI_ACPI_5_0_MEMORY_AFFINITY_STRUCTURE

EFI_ACPI_5_1_MEMORY_ENABLED       = (1 << 0)
EFI_ACPI_5_1_MEMORY_HOT_PLUGGABLE = (1 << 1)
EFI_ACPI_5_1_MEMORY_NONVOLATILE   = (1 << 2)

EFI_ACPI_5_1_PROCESSOR_LOCAL_X2APIC_AFFINITY_STRUCTURE = EFI_ACPI_5_0_PROCESSOR_LOCAL_X2APIC_AFFINITY_STRUCTURE

class EFI_ACPI_5_1_GICC_AFFINITY_STRUCTURE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("Type",              UINT8),
    ("Length",            UINT8),
    ("ProximityDomain",   UINT32),
    ("AcpiProcessorUid",  UINT32),
    ("Flags",             UINT32),
    ("ClockDomain",       UINT32)
  ]

EFI_ACPI_5_1_GICC_ENABLED = (1 << 0)

EFI_ACPI_5_1_SYSTEM_LOCALITY_DISTANCE_INFORMATION_TABLE_HEADER = EFI_ACPI_5_0_SYSTEM_LOCALITY_DISTANCE_INFORMATION_TABLE_HEADER

EFI_ACPI_5_1_SYSTEM_LOCALITY_DISTANCE_INFORMATION_TABLE_REVISION  = 0x01

EFI_ACPI_5_1_CORRECTED_PLATFORM_ERROR_POLLING_TABLE_HEADER = EFI_ACPI_5_0_CORRECTED_PLATFORM_ERROR_POLLING_TABLE_HEADER

EFI_ACPI_5_1_CORRECTED_PLATFORM_ERROR_POLLING_TABLE_REVISION = 0x01

EFI_ACPI_5_1_CPEP_PROCESSOR_APIC_SAPIC  = 0x00

EFI_ACPI_5_1_CPEP_PROCESSOR_APIC_SAPIC_STRUCTURE = EFI_ACPI_5_0_CPEP_PROCESSOR_APIC_SAPIC_STRUCTURE

EFI_ACPI_5_1_MAXIMUM_SYSTEM_CHARACTERISTICS_TABLE_HEADER = EFI_ACPI_5_0_MAXIMUM_SYSTEM_CHARACTERISTICS_TABLE_HEADER

EFI_ACPI_5_1_MAXIMUM_SYSTEM_CHARACTERISTICS_TABLE_REVISION = 0x01

EFI_ACPI_5_1_MAXIMUM_PROXIMITY_DOMAIN_INFORMATION_STRUCTURE = EFI_ACPI_5_0_MAXIMUM_PROXIMITY_DOMAIN_INFORMATION_STRUCTURE

EFI_ACPI_5_1_RAS_FEATURE_TABLE = EFI_ACPI_5_0_RAS_FEATURE_TABLE

EFI_ACPI_5_1_RAS_FEATURE_TABLE_REVISION = 0x01

EFI_ACPI_5_1_RASF_PLATFORM_COMMUNICATION_CHANNEL_SHARED_MEMORY_REGION = EFI_ACPI_5_0_RASF_PLATFORM_COMMUNICATION_CHANNEL_SHARED_MEMORY_REGION

EFI_ACPI_5_1_RASF_PCC_COMMAND_CODE_EXECUTE_RASF_COMMAND  = 0x01

EFI_ACPI_5_1_RASF_PLATFORM_RAS_CAPABILITY_HARDWARE_BASED_PATROL_SCRUB_SUPPOTED                          = 0x01
EFI_ACPI_5_1_RASF_PLATFORM_RAS_CAPABILITY_HARDWARE_BASED_PATROL_SCRUB_SUPPOTED_AND_EXPOSED_TO_SOFTWARE  = 0x02

EFI_ACPI_5_1_RASF_PATROL_SCRUB_PLATFORM_BLOCK_STRUCTURE = EFI_ACPI_5_0_RASF_PATROL_SCRUB_PLATFORM_BLOCK_STRUCTURE

EFI_ACPI_5_1_RASF_PATROL_SCRUB_COMMAND_GET_PATROL_PARAMETERS   = 0x01
EFI_ACPI_5_1_RASF_PATROL_SCRUB_COMMAND_START_PATROL_SCRUBBER   = 0x02
EFI_ACPI_5_1_RASF_PATROL_SCRUB_COMMAND_STOP_PATROL_SCRUBBER    = 0x03

EFI_ACPI_5_1_MEMORY_POWER_STATUS_TABLE = EFI_ACPI_5_0_MEMORY_POWER_STATUS_TABLE

EFI_ACPI_5_1_MEMORY_POWER_STATE_TABLE_REVISION = 0x01

EFI_ACPI_5_1_MPST_PLATFORM_COMMUNICATION_CHANNEL_SHARED_MEMORY_REGION = EFI_ACPI_5_0_MPST_PLATFORM_COMMUNICATION_CHANNEL_SHARED_MEMORY_REGION

EFI_ACPI_5_1_MPST_PCC_COMMAND_CODE_EXECUTE_MPST_COMMAND  = 0x03

EFI_ACPI_5_1_MPST_MEMORY_POWER_COMMAND_GET_MEMORY_POWER_STATE       = 0x01
EFI_ACPI_5_1_MPST_MEMORY_POWER_COMMAND_SET_MEMORY_POWER_STATE       = 0x02
EFI_ACPI_5_1_MPST_MEMORY_POWER_COMMAND_GET_AVERAGE_POWER_CONSUMED   = 0x03
EFI_ACPI_5_1_MPST_MEMORY_POWER_COMMAND_GET_MEMORY_ENERGY_CONSUMED   = 0x04

EFI_ACPI_5_1_MPST_MEMORY_POWER_STATE = EFI_ACPI_5_0_MPST_MEMORY_POWER_STATE

EFI_ACPI_5_1_MPST_MEMORY_POWER_STRUCTURE = EFI_ACPI_5_0_MPST_MEMORY_POWER_STRUCTURE

EFI_ACPI_5_1_MPST_MEMORY_POWER_STRUCTURE_FLAG_ENABLE          = 0x01
EFI_ACPI_5_1_MPST_MEMORY_POWER_STRUCTURE_FLAG_POWER_MANAGED   = 0x02
EFI_ACPI_5_1_MPST_MEMORY_POWER_STRUCTURE_FLAG_HOT_PLUGGABLE   = 0x04

EFI_ACPI_5_1_MPST_MEMORY_POWER_NODE_TABLE = EFI_ACPI_5_0_MPST_MEMORY_POWER_NODE_TABLE

EFI_ACPI_5_1_MPST_MEMORY_POWER_STATE_CHARACTERISTICS_STRUCTURE = EFI_ACPI_5_0_MPST_MEMORY_POWER_STATE_CHARACTERISTICS_STRUCTURE

EFI_ACPI_5_1_MPST_MEMORY_POWER_STATE_CHARACTERISTICS_STRUCTURE_FLAG_MEMORY_CONTENT_PRESERVED              = 0x01
EFI_ACPI_5_1_MPST_MEMORY_POWER_STATE_CHARACTERISTICS_STRUCTURE_FLAG_AUTONOMOUS_MEMORY_POWER_STATE_ENTRY   = 0x02
EFI_ACPI_5_1_MPST_MEMORY_POWER_STATE_CHARACTERISTICS_STRUCTURE_FLAG_AUTONOMOUS_MEMORY_POWER_STATE_EXIT    = 0x04

EFI_ACPI_5_1_MPST_MEMORY_POWER_STATE_CHARACTERISTICS_TABLE = EFI_ACPI_5_0_MPST_MEMORY_POWER_STATE_CHARACTERISTICS_TABLE

EFI_ACPI_5_1_MEMORY_TOPOLOGY_TABLE = EFI_ACPI_5_0_MEMORY_TOPOLOGY_TABLE

EFI_ACPI_5_1_MEMORY_TOPOLOGY_TABLE_REVISION = 0x01

EFI_ACPI_5_1_PMMT_COMMON_MEMORY_AGGREGATOR_DEVICE_STRUCTURE = EFI_ACPI_5_0_PMMT_COMMON_MEMORY_AGGREGATOR_DEVICE_STRUCTURE

EFI_ACPI_5_1_PMMT_MEMORY_AGGREGATOR_DEVICE_TYPE_SOCKET            = 0x1
EFI_ACPI_5_1_PMMT_MEMORY_AGGREGATOR_DEVICE_TYPE_MEMORY_CONTROLLER = 0x2
EFI_ACPI_5_1_PMMT_MEMORY_AGGREGATOR_DEVICE_TYPE_DIMM              = 0x3

EFI_ACPI_5_1_PMMT_SOCKET_MEMORY_AGGREGATOR_DEVICE_STRUCTURE = EFI_ACPI_5_0_PMMT_SOCKET_MEMORY_AGGREGATOR_DEVICE_STRUCTURE

EFI_ACPI_5_1_PMMT_MEMORY_CONTROLLER_MEMORY_AGGREGATOR_DEVICE_STRUCTURE = EFI_ACPI_5_0_PMMT_MEMORY_CONTROLLER_MEMORY_AGGREGATOR_DEVICE_STRUCTURE

EFI_ACPI_5_1_PMMT_DIMM_MEMORY_AGGREGATOR_DEVICE_STRUCTURE = EFI_ACPI_5_0_PMMT_DIMM_MEMORY_AGGREGATOR_DEVICE_STRUCTURE

EFI_ACPI_5_1_BOOT_GRAPHICS_RESOURCE_TABLE = EFI_ACPI_5_0_BOOT_GRAPHICS_RESOURCE_TABLE

EFI_ACPI_5_1_BOOT_GRAPHICS_RESOURCE_TABLE_REVISION = 1

EFI_ACPI_5_1_BGRT_VERSION         = 0x01

EFI_ACPI_5_1_BGRT_STATUS_NOT_DISPLAYED = 0x00
EFI_ACPI_5_1_BGRT_STATUS_DISPLAYED     = 0x01

EFI_ACPI_5_1_BGRT_IMAGE_TYPE_BMP  = 0x00

EFI_ACPI_5_1_FIRMWARE_PERFORMANCE_DATA_TABLE_REVISION = 0x01

EFI_ACPI_5_1_FPDT_RECORD_TYPE_FIRMWARE_BASIC_BOOT_POINTER      = 0x0000
EFI_ACPI_5_1_FPDT_RECORD_TYPE_S3_PERFORMANCE_TABLE_POINTER     = 0x0001

EFI_ACPI_5_1_FPDT_RECORD_REVISION_FIRMWARE_BASIC_BOOT_POINTER  = 0x01
EFI_ACPI_5_1_FPDT_RECORD_REVISION_S3_PERFORMANCE_TABLE_POINTER = 0x01

EFI_ACPI_5_1_FPDT_RUNTIME_RECORD_TYPE_S3_RESUME                = 0x0000
EFI_ACPI_5_1_FPDT_RUNTIME_RECORD_TYPE_S3_SUSPEND               = 0x0001
EFI_ACPI_5_1_FPDT_RUNTIME_RECORD_TYPE_FIRMWARE_BASIC_BOOT      = 0x0002

EFI_ACPI_5_1_FPDT_RUNTIME_RECORD_REVISION_S3_RESUME            = 0x01
EFI_ACPI_5_1_FPDT_RUNTIME_RECORD_REVISION_S3_SUSPEND           = 0x01
EFI_ACPI_5_1_FPDT_RUNTIME_RECORD_REVISION_FIRMWARE_BASIC_BOOT  = 0x02

EFI_ACPI_5_1_FPDT_PERFORMANCE_RECORD_HEADER = EFI_ACPI_5_0_FPDT_PERFORMANCE_RECORD_HEADER

EFI_ACPI_5_1_FPDT_PERFORMANCE_TABLE_HEADER = EFI_ACPI_5_0_FPDT_PERFORMANCE_TABLE_HEADER

EFI_ACPI_5_1_FPDT_BOOT_PERFORMANCE_TABLE_POINTER_RECORD = EFI_ACPI_5_0_FPDT_BOOT_PERFORMANCE_TABLE_POINTER_RECORD

EFI_ACPI_5_1_FPDT_S3_PERFORMANCE_TABLE_POINTER_RECORD = EFI_ACPI_5_0_FPDT_S3_PERFORMANCE_TABLE_POINTER_RECORD

EFI_ACPI_5_1_FPDT_FIRMWARE_BASIC_BOOT_RECORD = EFI_ACPI_5_0_FPDT_FIRMWARE_BASIC_BOOT_RECORD

EFI_ACPI_5_1_FPDT_BOOT_PERFORMANCE_TABLE_SIGNATURE  = SIGNATURE_32('F', 'B', 'P', 'T')
EFI_ACPI_5_1_FPDT_FIRMWARE_BASIC_BOOT_TABLE = EFI_ACPI_5_0_FPDT_FIRMWARE_BASIC_BOOT_TABLE

EFI_ACPI_5_1_FPDT_S3_PERFORMANCE_TABLE_SIGNATURE  = SIGNATURE_32('S', '3', 'P', 'T')
EFI_ACPI_5_1_FPDT_FIRMWARE_S3_BOOT_TABLE = EFI_ACPI_5_0_FPDT_FIRMWARE_S3_BOOT_TABLE

EFI_ACPI_5_1_FPDT_S3_RESUME_RECORD = EFI_ACPI_5_0_FPDT_S3_RESUME_RECORD

EFI_ACPI_5_1_FPDT_S3_SUSPEND_RECORD = EFI_ACPI_5_0_FPDT_S3_SUSPEND_RECORD

EFI_ACPI_5_1_FIRMWARE_PERFORMANCE_RECORD_TABLE = EFI_ACPI_5_0_FIRMWARE_PERFORMANCE_RECORD_TABLE

class EFI_ACPI_5_1_GENERIC_TIMER_DESCRIPTION_TABLE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("CntControlBasePhysicalAddress", UINT64),
    ("Reserved",                      UINT32),
    ("SecurePL1TimerGSIV",            UINT32),
    ("SecurePL1TimerFlags",           UINT32),
    ("NonSecurePL1TimerGSIV",         UINT32),
    ("NonSecurePL1TimerFlags",        UINT32),
    ("VirtualTimerGSIV",              UINT32),
    ("VirtualTimerFlags",             UINT32),
    ("NonSecurePL2TimerGSIV",         UINT32),
    ("NonSecurePL2TimerFlags",        UINT32),
    ("CntReadBasePhysicalAddress",    UINT64),
    ("PlatformTimerCount",            UINT32),
    ("PlatformTimerOffset",           UINT32)
  ]

EFI_ACPI_5_1_GENERIC_TIMER_DESCRIPTION_TABLE_REVISION = 0x02
EFI_ACPI_5_1_GTDT_TIMER_FLAG_TIMER_INTERRUPT_MODE          = BIT0
EFI_ACPI_5_1_GTDT_TIMER_FLAG_TIMER_INTERRUPT_POLARITY      = BIT1
EFI_ACPI_5_1_GTDT_TIMER_FLAG_ALWAYS_ON_CAPABILITY          = BIT2

EFI_ACPI_5_1_GTDT_GT_BLOCK                       = 0
EFI_ACPI_5_1_GTDT_SBSA_GENERIC_WATCHDOG          = 1

class EFI_ACPI_5_1_GTDT_GT_BLOCK_STRUCTURE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("Type",                UINT8),
    ("Length",              UINT16),
    ("Reserved",            UINT8),
    ("CntCtlBase",          UINT64),
    ("GTBlockTimerCount",   UINT32),
    ("GTBlockTimerOffset",  UINT32)
  ]

class EFI_ACPI_5_1_GTDT_GT_BLOCK_TIMER_STRUCTURE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("GTFrameNumber",         UINT8),
    ("Reserved",              UINT8 * 3),
    ("CntBaseX",              UINT64),
    ("CntEL0BaseX",           UINT64),
    ("GTxPhysicalTimerGSIV",  UINT32),
    ("GTxPhysicalTimerFlags", UINT32),
    ("GTxVirtualTimerGSIV",   UINT32),
    ("GTxVirtualTimerFlags",  UINT32),
    ("GTxCommonFlags",        UINT32)
  ]

EFI_ACPI_5_1_GTDT_GT_BLOCK_TIMER_FLAG_TIMER_INTERRUPT_MODE          = BIT0
EFI_ACPI_5_1_GTDT_GT_BLOCK_TIMER_FLAG_TIMER_INTERRUPT_POLARITY      = BIT1

EFI_ACPI_5_1_GTDT_GT_BLOCK_COMMON_FLAG_SECURE_TIMER              = BIT0
EFI_ACPI_5_1_GTDT_GT_BLOCK_COMMON_FLAG_ALWAYS_ON_CAPABILITY      = BIT1

class EFI_ACPI_5_1_GTDT_SBSA_GENERIC_WATCHDOG_STRUCTURE (EFIPY_INDUSTRY_STRUCTURE):
  _fields_ = [
    ("Type",                                UINT8),
    ("Length",                              UINT16),
    ("Reserved",                            UINT8),
    ("RefreshFramePhysicalAddress",         UINT64),
    ("WatchdogControlFramePhysicalAddress", UINT64),
    ("WatchdogTimerGSIV",                   UINT32),
    ("WatchdogTimerFlags",                  UINT32)
  ]

EFI_ACPI_5_1_GTDT_SBSA_GENERIC_WATCHDOG_FLAG_TIMER_INTERRUPT_MODE          = BIT0
EFI_ACPI_5_1_GTDT_SBSA_GENERIC_WATCHDOG_FLAG_TIMER_INTERRUPT_POLARITY      = BIT1
EFI_ACPI_5_1_GTDT_SBSA_GENERIC_WATCHDOG_FLAG_SECURE_TIMER                  = BIT2

EFI_ACPI_5_1_BOOT_ERROR_RECORD_TABLE_HEADER = EFI_ACPI_5_0_BOOT_ERROR_RECORD_TABLE_HEADER

EFI_ACPI_5_1_BOOT_ERROR_RECORD_TABLE_REVISION = EFI_ACPI_5_0_BOOT_ERROR_RECORD_TABLE_REVISION

EFI_ACPI_5_1_ERROR_BLOCK_STATUS = EFI_ACPI_5_0_ERROR_BLOCK_STATUS

EFI_ACPI_5_1_BOOT_ERROR_REGION_STRUCTURE = EFI_ACPI_5_0_BOOT_ERROR_REGION_STRUCTURE

EFI_ACPI_5_1_ERROR_SEVERITY_CORRECTABLE  = EFI_ACPI_5_0_ERROR_SEVERITY_CORRECTABLE
EFI_ACPI_5_1_ERROR_SEVERITY_FATAL        = EFI_ACPI_5_0_ERROR_SEVERITY_FATAL
EFI_ACPI_5_1_ERROR_SEVERITY_CORRECTED    = EFI_ACPI_5_0_ERROR_SEVERITY_CORRECTED
EFI_ACPI_5_1_ERROR_SEVERITY_NONE         = EFI_ACPI_5_0_ERROR_SEVERITY_NONE

EFI_ACPI_5_1_GENERIC_ERROR_DATA_ENTRY_STRUCTURE = EFI_ACPI_5_0_GENERIC_ERROR_DATA_ENTRY_STRUCTURE

EFI_ACPI_5_1_GENERIC_ERROR_DATA_ENTRY_REVISION  = EFI_ACPI_5_0_GENERIC_ERROR_DATA_ENTRY_REVISION

EFI_ACPI_5_1_HARDWARE_ERROR_SOURCE_TABLE_HEADER = EFI_ACPI_5_0_HARDWARE_ERROR_SOURCE_TABLE_HEADER

EFI_ACPI_5_1_HARDWARE_ERROR_SOURCE_TABLE_REVISION = 0x01

EFI_ACPI_5_1_IA32_ARCHITECTURE_MACHINE_CHECK_EXCEPTION  = EFI_ACPI_5_0_IA32_ARCHITECTURE_MACHINE_CHECK_EXCEPTION
EFI_ACPI_5_1_IA32_ARCHITECTURE_CORRECTED_MACHINE_CHECK  = EFI_ACPI_5_0_IA32_ARCHITECTURE_CORRECTED_MACHINE_CHECK
EFI_ACPI_5_1_IA32_ARCHITECTURE_NMI_ERROR                = EFI_ACPI_5_0_IA32_ARCHITECTURE_NMI_ERROR
EFI_ACPI_5_1_PCI_EXPRESS_ROOT_PORT_AER                  = EFI_ACPI_5_0_PCI_EXPRESS_ROOT_PORT_AER
EFI_ACPI_5_1_PCI_EXPRESS_DEVICE_AER                     = EFI_ACPI_5_0_PCI_EXPRESS_DEVICE_AER
EFI_ACPI_5_1_PCI_EXPRESS_BRIDGE_AER                     = EFI_ACPI_5_0_PCI_EXPRESS_BRIDGE_AER
EFI_ACPI_5_1_GENERIC_HARDWARE_ERROR                     = EFI_ACPI_5_0_GENERIC_HARDWARE_ERROR

EFI_ACPI_5_1_ERROR_SOURCE_FLAG_FIRMWARE_FIRST       = EFI_ACPI_5_0_ERROR_SOURCE_FLAG_FIRMWARE_FIRST
EFI_ACPI_5_1_ERROR_SOURCE_FLAG_GLOBAL               = EFI_ACPI_5_0_ERROR_SOURCE_FLAG_GLOBAL

EFI_ACPI_5_1_IA32_ARCHITECTURE_MACHINE_CHECK_EXCEPTION_STRUCTURE = EFI_ACPI_5_0_IA32_ARCHITECTURE_MACHINE_CHECK_EXCEPTION_STRUCTURE

EFI_ACPI_5_1_IA32_ARCHITECTURE_MACHINE_CHECK_ERROR_BANK_STRUCTURE = EFI_ACPI_5_0_IA32_ARCHITECTURE_MACHINE_CHECK_ERROR_BANK_STRUCTURE

EFI_ACPI_5_1_IA32_ARCHITECTURE_MACHINE_CHECK_ERROR_DATA_FORMAT_IA32      = EFI_ACPI_5_0_IA32_ARCHITECTURE_MACHINE_CHECK_ERROR_DATA_FORMAT_IA32
EFI_ACPI_5_1_IA32_ARCHITECTURE_MACHINE_CHECK_ERROR_DATA_FORMAT_INTEL64   = EFI_ACPI_5_0_IA32_ARCHITECTURE_MACHINE_CHECK_ERROR_DATA_FORMAT_INTEL64
EFI_ACPI_5_1_IA32_ARCHITECTURE_MACHINE_CHECK_ERROR_DATA_FORMAT_AMD64     = EFI_ACPI_5_0_IA32_ARCHITECTURE_MACHINE_CHECK_ERROR_DATA_FORMAT_AMD64

EFI_ACPI_5_1_HARDWARE_ERROR_NOTIFICATION_POLLED                = EFI_ACPI_5_0_HARDWARE_ERROR_NOTIFICATION_POLLED
EFI_ACPI_5_1_HARDWARE_ERROR_NOTIFICATION_EXTERNAL_INTERRUPT    = EFI_ACPI_5_0_HARDWARE_ERROR_NOTIFICATION_EXTERNAL_INTERRUPT
EFI_ACPI_5_1_HARDWARE_ERROR_NOTIFICATION_LOCAL_INTERRUPT       = EFI_ACPI_5_0_HARDWARE_ERROR_NOTIFICATION_LOCAL_INTERRUPT
EFI_ACPI_5_1_HARDWARE_ERROR_NOTIFICATION_SCI                   = EFI_ACPI_5_0_HARDWARE_ERROR_NOTIFICATION_SCI
EFI_ACPI_5_1_HARDWARE_ERROR_NOTIFICATION_NMI                   = EFI_ACPI_5_0_HARDWARE_ERROR_NOTIFICATION_NMI

EFI_ACPI_5_1_HARDWARE_ERROR_NOTIFICATION_CONFIGURATION_WRITE_ENABLE_STRUCTURE = EFI_ACPI_5_0_HARDWARE_ERROR_NOTIFICATION_CONFIGURATION_WRITE_ENABLE_STRUCTURE

EFI_ACPI_5_1_HARDWARE_ERROR_NOTIFICATION_STRUCTURE = EFI_ACPI_5_0_HARDWARE_ERROR_NOTIFICATION_STRUCTURE

EFI_ACPI_5_1_IA32_ARCHITECTURE_CORRECTED_MACHINE_CHECK_STRUCTURE = EFI_ACPI_5_0_IA32_ARCHITECTURE_CORRECTED_MACHINE_CHECK_STRUCTURE

EFI_ACPI_5_1_IA32_ARCHITECTURE_NMI_ERROR_STRUCTURE = EFI_ACPI_5_0_IA32_ARCHITECTURE_NMI_ERROR_STRUCTURE

EFI_ACPI_5_1_PCI_EXPRESS_ROOT_PORT_AER_STRUCTURE = EFI_ACPI_5_0_PCI_EXPRESS_ROOT_PORT_AER_STRUCTURE

EFI_ACPI_5_1_PCI_EXPRESS_DEVICE_AER_STRUCTURE = EFI_ACPI_5_0_PCI_EXPRESS_DEVICE_AER_STRUCTURE

EFI_ACPI_5_1_PCI_EXPRESS_BRIDGE_AER_STRUCTURE = EFI_ACPI_5_0_PCI_EXPRESS_BRIDGE_AER_STRUCTURE

EFI_ACPI_5_1_GENERIC_HARDWARE_ERROR_SOURCE_STRUCTURE = EFI_ACPI_5_0_GENERIC_HARDWARE_ERROR_SOURCE_STRUCTURE

EFI_ACPI_5_1_GENERIC_ERROR_STATUS_STRUCTURE = EFI_ACPI_5_0_GENERIC_ERROR_STATUS_STRUCTURE

EFI_ACPI_5_1_ERROR_RECORD_SERIALIZATION_TABLE_HEADER = EFI_ACPI_5_0_ERROR_RECORD_SERIALIZATION_TABLE_HEADER

EFI_ACPI_5_1_ERROR_RECORD_SERIALIZATION_TABLE_REVISION = 0x01

EFI_ACPI_5_1_ERST_BEGIN_WRITE_OPERATION                    = EFI_ACPI_5_0_ERST_BEGIN_WRITE_OPERATION
EFI_ACPI_5_1_ERST_BEGIN_READ_OPERATION                     = EFI_ACPI_5_0_ERST_BEGIN_READ_OPERATION
EFI_ACPI_5_1_ERST_BEGIN_CLEAR_OPERATION                    = EFI_ACPI_5_0_ERST_BEGIN_CLEAR_OPERATION
EFI_ACPI_5_1_ERST_END_OPERATION                            = EFI_ACPI_5_0_ERST_END_OPERATION
EFI_ACPI_5_1_ERST_SET_RECORD_OFFSET                        = EFI_ACPI_5_0_ERST_SET_RECORD_OFFSET
EFI_ACPI_5_1_ERST_EXECUTE_OPERATION                        = EFI_ACPI_5_0_ERST_EXECUTE_OPERATION
EFI_ACPI_5_1_ERST_CHECK_BUSY_STATUS                        = EFI_ACPI_5_0_ERST_CHECK_BUSY_STATUS
EFI_ACPI_5_1_ERST_GET_COMMAND_STATUS                       = EFI_ACPI_5_0_ERST_GET_COMMAND_STATUS
EFI_ACPI_5_1_ERST_GET_RECORD_IDENTIFIER                    = EFI_ACPI_5_0_ERST_GET_RECORD_IDENTIFIER
EFI_ACPI_5_1_ERST_SET_RECORD_IDENTIFIER                    = EFI_ACPI_5_0_ERST_SET_RECORD_IDENTIFIER
EFI_ACPI_5_1_ERST_GET_RECORD_COUNT                         = EFI_ACPI_5_0_ERST_GET_RECORD_COUNT
EFI_ACPI_5_1_ERST_BEGIN_DUMMY_WRITE_OPERATION              = EFI_ACPI_5_0_ERST_BEGIN_DUMMY_WRITE_OPERATION
EFI_ACPI_5_1_ERST_GET_ERROR_LOG_ADDRESS_RANGE              = EFI_ACPI_5_0_ERST_GET_ERROR_LOG_ADDRESS_RANGE
EFI_ACPI_5_1_ERST_GET_ERROR_LOG_ADDRESS_RANGE_LENGTH       = EFI_ACPI_5_0_ERST_GET_ERROR_LOG_ADDRESS_RANGE_LENGTH
EFI_ACPI_5_1_ERST_GET_ERROR_LOG_ADDRESS_RANGE_ATTRIBUTES   = EFI_ACPI_5_0_ERST_GET_ERROR_LOG_ADDRESS_RANGE_ATTRIBUTES

EFI_ACPI_5_1_ERST_STATUS_SUCCESS                           = EFI_ACPI_5_0_ERST_STATUS_SUCCESS
EFI_ACPI_5_1_ERST_STATUS_NOT_ENOUGH_SPACE                  = EFI_ACPI_5_0_ERST_STATUS_NOT_ENOUGH_SPACE
EFI_ACPI_5_1_ERST_STATUS_HARDWARE_NOT_AVAILABLE            = EFI_ACPI_5_0_ERST_STATUS_HARDWARE_NOT_AVAILABLE
EFI_ACPI_5_1_ERST_STATUS_FAILED                            = EFI_ACPI_5_0_ERST_STATUS_FAILED
EFI_ACPI_5_1_ERST_STATUS_RECORD_STORE_EMPTY                = EFI_ACPI_5_0_ERST_STATUS_RECORD_STORE_EMPTY
EFI_ACPI_5_1_ERST_STATUS_RECORD_NOT_FOUND                  = EFI_ACPI_5_0_ERST_STATUS_RECORD_NOT_FOUND

EFI_ACPI_5_1_ERST_READ_REGISTER                            = EFI_ACPI_5_0_ERST_READ_REGISTER
EFI_ACPI_5_1_ERST_READ_REGISTER_VALUE                      = EFI_ACPI_5_0_ERST_READ_REGISTER_VALUE
EFI_ACPI_5_1_ERST_WRITE_REGISTER                           = EFI_ACPI_5_0_ERST_WRITE_REGISTER
EFI_ACPI_5_1_ERST_WRITE_REGISTER_VALUE                     = EFI_ACPI_5_0_ERST_WRITE_REGISTER_VALUE
EFI_ACPI_5_1_ERST_NOOP                                     = EFI_ACPI_5_0_ERST_NOOP
EFI_ACPI_5_1_ERST_LOAD_VAR1                                = EFI_ACPI_5_0_ERST_LOAD_VAR1
EFI_ACPI_5_1_ERST_LOAD_VAR2                                = EFI_ACPI_5_0_ERST_LOAD_VAR2
EFI_ACPI_5_1_ERST_STORE_VAR1                               = EFI_ACPI_5_0_ERST_STORE_VAR1
EFI_ACPI_5_1_ERST_ADD                                      = EFI_ACPI_5_0_ERST_ADD
EFI_ACPI_5_1_ERST_SUBTRACT                                 = EFI_ACPI_5_0_ERST_SUBTRACT
EFI_ACPI_5_1_ERST_ADD_VALUE                                = EFI_ACPI_5_0_ERST_ADD_VALUE
EFI_ACPI_5_1_ERST_SUBTRACT_VALUE                           = EFI_ACPI_5_0_ERST_SUBTRACT_VALUE
EFI_ACPI_5_1_ERST_STALL                                    = EFI_ACPI_5_0_ERST_STALL
EFI_ACPI_5_1_ERST_STALL_WHILE_TRUE                         = EFI_ACPI_5_0_ERST_STALL_WHILE_TRUE
EFI_ACPI_5_1_ERST_SKIP_NEXT_INSTRUCTION_IF_TRUE            = EFI_ACPI_5_0_ERST_SKIP_NEXT_INSTRUCTION_IF_TRUE
EFI_ACPI_5_1_ERST_GOTO                                     = EFI_ACPI_5_0_ERST_GOTO
EFI_ACPI_5_1_ERST_SET_SRC_ADDRESS_BASE                     = EFI_ACPI_5_0_ERST_SET_SRC_ADDRESS_BASE
EFI_ACPI_5_1_ERST_SET_DST_ADDRESS_BASE                     = EFI_ACPI_5_0_ERST_SET_DST_ADDRESS_BASE
EFI_ACPI_5_1_ERST_MOVE_DATA                                = EFI_ACPI_5_0_ERST_MOVE_DATA

EFI_ACPI_5_1_ERST_PRESERVE_REGISTER                        = EFI_ACPI_5_0_ERST_PRESERVE_REGISTER

EFI_ACPI_5_1_ERST_SERIALIZATION_INSTRUCTION_ENTRY = EFI_ACPI_5_0_ERST_SERIALIZATION_INSTRUCTION_ENTRY

EFI_ACPI_5_1_ERROR_INJECTION_TABLE_HEADER = EFI_ACPI_5_0_ERROR_INJECTION_TABLE_HEADER

EFI_ACPI_5_1_ERROR_INJECTION_TABLE_REVISION = EFI_ACPI_5_0_ERROR_INJECTION_TABLE_REVISION

EFI_ACPI_5_1_EINJ_BEGIN_INJECTION_OPERATION                = EFI_ACPI_5_0_EINJ_BEGIN_INJECTION_OPERATION
EFI_ACPI_5_1_EINJ_GET_TRIGGER_ERROR_ACTION_TABLE           = EFI_ACPI_5_0_EINJ_GET_TRIGGER_ERROR_ACTION_TABLE
EFI_ACPI_5_1_EINJ_SET_ERROR_TYPE                           = EFI_ACPI_5_0_EINJ_SET_ERROR_TYPE
EFI_ACPI_5_1_EINJ_GET_ERROR_TYPE                           = EFI_ACPI_5_0_EINJ_GET_ERROR_TYPE
EFI_ACPI_5_1_EINJ_END_OPERATION                            = EFI_ACPI_5_0_EINJ_END_OPERATION
EFI_ACPI_5_1_EINJ_EXECUTE_OPERATION                        = EFI_ACPI_5_0_EINJ_EXECUTE_OPERATION
EFI_ACPI_5_1_EINJ_CHECK_BUSY_STATUS                        = EFI_ACPI_5_0_EINJ_CHECK_BUSY_STATUS
EFI_ACPI_5_1_EINJ_GET_COMMAND_STATUS                       = EFI_ACPI_5_0_EINJ_GET_COMMAND_STATUS
EFI_ACPI_5_1_EINJ_TRIGGER_ERROR                            = EFI_ACPI_5_0_EINJ_TRIGGER_ERROR

EFI_ACPI_5_1_EINJ_STATUS_SUCCESS                           = EFI_ACPI_5_0_EINJ_STATUS_SUCCESS
EFI_ACPI_5_1_EINJ_STATUS_UNKNOWN_FAILURE                   = EFI_ACPI_5_0_EINJ_STATUS_UNKNOWN_FAILURE
EFI_ACPI_5_1_EINJ_STATUS_INVALID_ACCESS                    = EFI_ACPI_5_0_EINJ_STATUS_INVALID_ACCESS

EFI_ACPI_5_1_EINJ_ERROR_PROCESSOR_CORRECTABLE                 = EFI_ACPI_5_0_EINJ_ERROR_PROCESSOR_CORRECTABLE
EFI_ACPI_5_1_EINJ_ERROR_PROCESSOR_UNCORRECTABLE_NONFATAL      = EFI_ACPI_5_0_EINJ_ERROR_PROCESSOR_UNCORRECTABLE_NONFATAL
EFI_ACPI_5_1_EINJ_ERROR_PROCESSOR_UNCORRECTABLE_FATAL         = EFI_ACPI_5_0_EINJ_ERROR_PROCESSOR_UNCORRECTABLE_FATAL
EFI_ACPI_5_1_EINJ_ERROR_MEMORY_CORRECTABLE                    = EFI_ACPI_5_0_EINJ_ERROR_MEMORY_CORRECTABLE
EFI_ACPI_5_1_EINJ_ERROR_MEMORY_UNCORRECTABLE_NONFATAL         = EFI_ACPI_5_0_EINJ_ERROR_MEMORY_UNCORRECTABLE_NONFATAL
EFI_ACPI_5_1_EINJ_ERROR_MEMORY_UNCORRECTABLE_FATAL            = EFI_ACPI_5_0_EINJ_ERROR_MEMORY_UNCORRECTABLE_FATAL
EFI_ACPI_5_1_EINJ_ERROR_PCI_EXPRESS_CORRECTABLE               = EFI_ACPI_5_0_EINJ_ERROR_PCI_EXPRESS_CORRECTABLE
EFI_ACPI_5_1_EINJ_ERROR_PCI_EXPRESS_UNCORRECTABLE_NONFATAL    = EFI_ACPI_5_0_EINJ_ERROR_PCI_EXPRESS_UNCORRECTABLE_NONFATAL
EFI_ACPI_5_1_EINJ_ERROR_PCI_EXPRESS_UNCORRECTABLE_FATAL       = EFI_ACPI_5_0_EINJ_ERROR_PCI_EXPRESS_UNCORRECTABLE_FATAL
EFI_ACPI_5_1_EINJ_ERROR_PLATFORM_CORRECTABLE                  = EFI_ACPI_5_0_EINJ_ERROR_PLATFORM_CORRECTABLE
EFI_ACPI_5_1_EINJ_ERROR_PLATFORM_UNCORRECTABLE_NONFATAL       = EFI_ACPI_5_0_EINJ_ERROR_PLATFORM_UNCORRECTABLE_NONFATAL
EFI_ACPI_5_1_EINJ_ERROR_PLATFORM_UNCORRECTABLE_FATAL          = EFI_ACPI_5_0_EINJ_ERROR_PLATFORM_UNCORRECTABLE_FATAL

EFI_ACPI_5_1_EINJ_READ_REGISTER                            = EFI_ACPI_5_0_EINJ_READ_REGISTER
EFI_ACPI_5_1_EINJ_READ_REGISTER_VALUE                      = EFI_ACPI_5_0_EINJ_READ_REGISTER_VALUE
EFI_ACPI_5_1_EINJ_WRITE_REGISTER                           = EFI_ACPI_5_0_EINJ_WRITE_REGISTER
EFI_ACPI_5_1_EINJ_WRITE_REGISTER_VALUE                     = EFI_ACPI_5_0_EINJ_WRITE_REGISTER_VALUE
EFI_ACPI_5_1_EINJ_NOOP                                     = EFI_ACPI_5_0_EINJ_NOOP

EFI_ACPI_5_1_EINJ_PRESERVE_REGISTER                        = EFI_ACPI_5_0_EINJ_PRESERVE_REGISTER

EFI_ACPI_5_1_EINJ_INJECTION_INSTRUCTION_ENTRY = EFI_ACPI_5_0_EINJ_INJECTION_INSTRUCTION_ENTRY

EFI_ACPI_5_1_EINJ_TRIGGER_ACTION_TABLE = EFI_ACPI_5_0_EINJ_TRIGGER_ACTION_TABLE

EFI_ACPI_5_1_PLATFORM_COMMUNICATION_CHANNEL_TABLE_HEADER = EFI_ACPI_5_0_PLATFORM_COMMUNICATION_CHANNEL_TABLE_HEADER

EFI_ACPI_5_1_PLATFORM_COMMUNICATION_CHANNEL_TABLE_REVISION = EFI_ACPI_5_0_PLATFORM_COMMUNICATION_CHANNEL_TABLE_REVISION

EFI_ACPI_5_1_PCCT_FLAGS_SCI_DOORBELL                      = EFI_ACPI_5_0_PCCT_FLAGS_SCI_DOORBELL

EFI_ACPI_5_1_PCCT_SUBSPACE_TYPE_GENERIC  = EFI_ACPI_5_0_PCCT_SUBSPACE_TYPE_GENERIC

EFI_ACPI_5_1_PCCT_SUBSPACE_HEADER = EFI_ACPI_5_0_PCCT_SUBSPACE_HEADER

EFI_ACPI_5_1_PCCT_SUBSPACE_GENERIC = EFI_ACPI_5_0_PCCT_SUBSPACE_GENERIC

EFI_ACPI_5_1_PCCT_GENERIC_SHARED_MEMORY_REGION_COMMAND = EFI_ACPI_5_0_PCCT_GENERIC_SHARED_MEMORY_REGION_COMMAND

EFI_ACPI_5_1_PCCT_GENERIC_SHARED_MEMORY_REGION_STATUS = EFI_ACPI_5_0_PCCT_GENERIC_SHARED_MEMORY_REGION_STATUS

EFI_ACPI_5_1_PCCT_GENERIC_SHARED_MEMORY_REGION_HEADER = EFI_ACPI_5_0_PCCT_GENERIC_SHARED_MEMORY_REGION_HEADER

EFI_ACPI_5_1_ROOT_SYSTEM_DESCRIPTION_POINTER_SIGNATURE  = EFI_ACPI_5_0_ROOT_SYSTEM_DESCRIPTION_POINTER_SIGNATURE
EFI_ACPI_5_1_MULTIPLE_APIC_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_MULTIPLE_APIC_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_BOOT_ERROR_RECORD_TABLE_SIGNATURE  = EFI_ACPI_5_0_BOOT_ERROR_RECORD_TABLE_SIGNATURE
EFI_ACPI_5_1_BOOT_GRAPHICS_RESOURCE_TABLE_SIGNATURE  = EFI_ACPI_5_0_BOOT_GRAPHICS_RESOURCE_TABLE_SIGNATURE
EFI_ACPI_5_1_CORRECTED_PLATFORM_ERROR_POLLING_TABLE_SIGNATURE  = EFI_ACPI_5_0_CORRECTED_PLATFORM_ERROR_POLLING_TABLE_SIGNATURE
EFI_ACPI_5_1_DIFFERENTIATED_SYSTEM_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_DIFFERENTIATED_SYSTEM_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_EMBEDDED_CONTROLLER_BOOT_RESOURCES_TABLE_SIGNATURE  = EFI_ACPI_5_0_EMBEDDED_CONTROLLER_BOOT_RESOURCES_TABLE_SIGNATURE
EFI_ACPI_5_1_ERROR_INJECTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_ERROR_INJECTION_TABLE_SIGNATURE
EFI_ACPI_5_1_ERROR_RECORD_SERIALIZATION_TABLE_SIGNATURE  = EFI_ACPI_5_0_ERROR_RECORD_SERIALIZATION_TABLE_SIGNATURE
EFI_ACPI_5_1_FIXED_ACPI_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_FIXED_ACPI_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_FIRMWARE_ACPI_CONTROL_STRUCTURE_SIGNATURE  = EFI_ACPI_5_0_FIRMWARE_ACPI_CONTROL_STRUCTURE_SIGNATURE
EFI_ACPI_5_1_FIRMWARE_PERFORMANCE_DATA_TABLE_SIGNATURE  = EFI_ACPI_5_0_FIRMWARE_PERFORMANCE_DATA_TABLE_SIGNATURE
EFI_ACPI_5_1_GENERIC_TIMER_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_GENERIC_TIMER_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_HARDWARE_ERROR_SOURCE_TABLE_SIGNATURE  = EFI_ACPI_5_0_HARDWARE_ERROR_SOURCE_TABLE_SIGNATURE
EFI_ACPI_5_1_MEMORY_POWER_STATE_TABLE_SIGNATURE  = EFI_ACPI_5_0_MEMORY_POWER_STATE_TABLE_SIGNATURE
EFI_ACPI_5_1_MAXIMUM_SYSTEM_CHARACTERISTICS_TABLE_SIGNATURE  = EFI_ACPI_5_0_MAXIMUM_SYSTEM_CHARACTERISTICS_TABLE_SIGNATURE
EFI_ACPI_5_1_PLATFORM_MEMORY_TOPOLOGY_TABLE_SIGNATURE  = EFI_ACPI_5_0_PLATFORM_MEMORY_TOPOLOGY_TABLE_SIGNATURE
EFI_ACPI_5_1_PERSISTENT_SYSTEM_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_PERSISTENT_SYSTEM_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_ACPI_RAS_FEATURE_TABLE_SIGNATURE  = EFI_ACPI_5_0_ACPI_RAS_FEATURE_TABLE_SIGNATURE
EFI_ACPI_5_1_ROOT_SYSTEM_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_ROOT_SYSTEM_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_SMART_BATTERY_SPECIFICATION_TABLE_SIGNATURE  = EFI_ACPI_5_0_SMART_BATTERY_SPECIFICATION_TABLE_SIGNATURE
EFI_ACPI_5_1_SYSTEM_LOCALITY_INFORMATION_TABLE_SIGNATURE  = EFI_ACPI_5_0_SYSTEM_LOCALITY_INFORMATION_TABLE_SIGNATURE
EFI_ACPI_5_1_SYSTEM_RESOURCE_AFFINITY_TABLE_SIGNATURE  = EFI_ACPI_5_0_SYSTEM_RESOURCE_AFFINITY_TABLE_SIGNATURE
EFI_ACPI_5_1_SECONDARY_SYSTEM_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_SECONDARY_SYSTEM_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_EXTENDED_SYSTEM_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_EXTENDED_SYSTEM_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_SIMPLE_BOOT_FLAG_TABLE_SIGNATURE  = EFI_ACPI_5_0_SIMPLE_BOOT_FLAG_TABLE_SIGNATURE
EFI_ACPI_5_1_CORE_SYSTEM_RESOURCE_TABLE_SIGNATURE  = EFI_ACPI_5_0_CORE_SYSTEM_RESOURCE_TABLE_SIGNATURE
EFI_ACPI_5_1_DEBUG_PORT_2_TABLE_SIGNATURE  = EFI_ACPI_5_0_DEBUG_PORT_2_TABLE_SIGNATURE
EFI_ACPI_5_1_DEBUG_PORT_TABLE_SIGNATURE  = EFI_ACPI_5_0_DEBUG_PORT_TABLE_SIGNATURE
EFI_ACPI_5_1_DMA_REMAPPING_TABLE_SIGNATURE  = EFI_ACPI_5_0_DMA_REMAPPING_TABLE_SIGNATURE
EFI_ACPI_5_1_DYNAMIC_ROOT_OF_TRUST_FOR_MEASUREMENT_TABLE_SIGNATURE  = EFI_ACPI_5_0_DYNAMIC_ROOT_OF_TRUST_FOR_MEASUREMENT_TABLE_SIGNATURE
EFI_ACPI_5_1_EVENT_TIMER_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_EVENT_TIMER_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_HIGH_PRECISION_EVENT_TIMER_TABLE_SIGNATURE  = EFI_ACPI_5_0_HIGH_PRECISION_EVENT_TIMER_TABLE_SIGNATURE
EFI_ACPI_5_1_ISCSI_BOOT_FIRMWARE_TABLE_SIGNATURE  = EFI_ACPI_5_0_ISCSI_BOOT_FIRMWARE_TABLE_SIGNATURE
EFI_ACPI_5_1_IO_VIRTUALIZATION_REPORTING_STRUCTURE_SIGNATURE  = EFI_ACPI_5_0_IO_VIRTUALIZATION_REPORTING_STRUCTURE_SIGNATURE
EFI_ACPI_5_1_IO_LOW_POWER_IDLE_TABLE_STRUCTURE_SIGNATURE  = SIGNATURE_32('L', 'P', 'I', 'T')
EFI_ACPI_5_1_PCI_EXPRESS_MEMORY_MAPPED_CONFIGURATION_SPACE_BASE_ADDRESS_DESCRIPTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_PCI_EXPRESS_MEMORY_MAPPED_CONFIGURATION_SPACE_BASE_ADDRESS_DESCRIPTION_TABLE_SIGNATURE
EFI_ACPI_5_1_MANAGEMENT_CONTROLLER_HOST_INTERFACE_TABLE_SIGNATURE  = EFI_ACPI_5_0_MANAGEMENT_CONTROLLER_HOST_INTERFACE_TABLE_SIGNATURE
EFI_ACPI_5_1_DATA_MANAGEMENT_TABLE_SIGNATURE  = EFI_ACPI_5_0_DATA_MANAGEMENT_TABLE_SIGNATURE
EFI_ACPI_5_1_SOFTWARE_LICENSING_TABLE_SIGNATURE  = EFI_ACPI_5_0_SOFTWARE_LICENSING_TABLE_SIGNATURE
EFI_ACPI_5_1_SERIAL_PORT_CONSOLE_REDIRECTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_SERIAL_PORT_CONSOLE_REDIRECTION_TABLE_SIGNATURE
EFI_ACPI_5_1_SERVER_PLATFORM_MANAGEMENT_INTERFACE_TABLE_SIGNATURE  = EFI_ACPI_5_0_SERVER_PLATFORM_MANAGEMENT_INTERFACE_TABLE_SIGNATURE
EFI_ACPI_5_1_TRUSTED_COMPUTING_PLATFORM_ALLIANCE_CAPABILITIES_TABLE_SIGNATURE  = EFI_ACPI_5_0_TRUSTED_COMPUTING_PLATFORM_ALLIANCE_CAPABILITIES_TABLE_SIGNATURE
EFI_ACPI_5_1_TRUSTED_COMPUTING_PLATFORM_2_TABLE_SIGNATURE  = EFI_ACPI_5_0_TRUSTED_COMPUTING_PLATFORM_2_TABLE_SIGNATURE
EFI_ACPI_5_1_UEFI_ACPI_DATA_TABLE_SIGNATURE  = EFI_ACPI_5_0_UEFI_ACPI_DATA_TABLE_SIGNATURE
EFI_ACPI_5_1_WINDOWS_ACPI_EMULATED_DEVICES_TABLE_SIGNATURE  = EFI_ACPI_5_0_WINDOWS_ACPI_EMULATED_DEVICES_TABLE_SIGNATURE
EFI_ACPI_5_1_WATCHDOG_ACTION_TABLE_SIGNATURE  = EFI_ACPI_5_0_WATCHDOG_ACTION_TABLE_SIGNATURE
EFI_ACPI_5_1_WATCHDOG_RESOURCE_TABLE_SIGNATURE  = EFI_ACPI_5_0_WATCHDOG_RESOURCE_TABLE_SIGNATURE
EFI_ACPI_5_1_PLATFORM_BINARY_TABLE_SIGNATURE  = EFI_ACPI_5_0_PLATFORM_BINARY_TABLE_SIGNATURE
