# PciCodeId.py
#
# EfiPy2.MdePkg.IndustryStandard.PciCodeId
#   part of EfiPy, EfiPy2
#
# Copyright (C) 2015 - 2023 MaxWu efipy.core@gmail.com
#   GPL-2.0
#
PCI_IF_MASS_STORAGE_SCSI_VENDOR_SPECIFIC          = 0x00
PCI_IF_MASS_STORAGE_SCSI_DEVICE_PQI               = 0x11
PCI_IF_MASS_STORAGE_SCSI_CONTROLLER_PQI           = 0x12
PCI_IF_MASS_STORAGE_SCSI_DEVICE_CONTROLLER_PQI    = 0x13
PCI_IF_MASS_STORAGE_SCSI_DEVICE_NVM_EXPRESS       = 0x21
PCI_IF_MASS_STORAGE_SATA_SERIAL_BUS               = 0x02
PCI_CLASS_MASS_STORAGE_SAS                        = 0x07
PCI_IF_MASS_STORAGE_SAS                           = 0x00
PCI_IF_MASS_STORAGE_SAS_SERIAL_BUS                = 0x01
PCI_CLASS_MASS_STORAGE_SOLID_STATE                = 0x08
PCI_IF_MASS_STORAGE_SOLID_STATE                   = 0x00
PCI_IF_MASS_STORAGE_SOLID_STATE_NVMHCI            = 0x01
PCI_IF_MASS_STORAGE_SOLID_STATE_ENTERPRISE_NVMHCI = 0x02

PCI_CLASS_NETWORK_INFINIBAND   = 0x07

PCI_CLASS_MEDIA_MIXED_MODE   = 0x03

PCI_CLASS_BRIDGE_ADVANCED_SWITCHING_TO_PCI      = 0x0B
PCI_IF_BRIDGE_ADVANCED_SWITCHING_TO_PCI_CUSTOM  = 0x00
PCI_IF_BRIDGE_ADVANCED_SWITCHING_TO_PCI_ASI_SIG = 0x01

PCI_IF_HPET                     = 0x03
PCI_SUBCLASS_SD_HOST_CONTROLLER = 0x05
PCI_SUBCLASS_IOMMU              = 0x06

PCI_SUBCLASS_PROC_OTHER = 0x80

PCI_IF_XHCI             = 0x30
PCI_CLASS_SERIAL_OTHER  = 0x80

PCI_SUBCLASS_SATELLITE_OTHER = 0x80

PCI_CLASS_PROCESSING_ACCELERATOR  = 0x12
