# GlobalVariable.py
#
# EfiPy2.MdePkg.Guid.GlobalVariable
#   part of EfiPy, EfiPy2
#
# Copyright (C) 2015 - 2023 MaxWu efipy.core@gmail.com
#   GPL-2.0
#
from EfiPy2 import *

gEfiGlobalVariableGuid  = EFI_GUID( 0x8BE4DF61, 0x93CA, 0x11d2, (0xAA, 0x0D, 0x00, 0xE0, 0x98, 0x03, 0x2B, 0x8C))

EFI_LANG_CODES_VARIABLE_NAME  = "LangCodes"

EFI_LANG_VARIABLE_NAME  = "Lang"

EFI_TIME_OUT_VARIABLE_NAME  = "Timeout"

EFI_PLATFORM_LANG_CODES_VARIABLE_NAME  = "PlatformLangCodes"

EFI_PLATFORM_LANG_VARIABLE_NAME  = "PlatformLang"

EFI_CON_IN_VARIABLE_NAME   = "ConIn"
EFI_CON_OUT_VARIABLE_NAME  = "ConOut"
EFI_ERR_OUT_VARIABLE_NAME  = "ErrOut"

EFI_CON_IN_DEV_VARIABLE_NAME   = "ConInDev"
EFI_CON_OUT_DEV_VARIABLE_NAME  = "ConOutDev"
EFI_ERR_OUT_DEV_VARIABLE_NAME  = "ErrOutDev"

EFI_BOOT_ORDER_VARIABLE_NAME  = "BootOrder"

EFI_BOOT_NEXT_VARIABLE_NAME  = "BootNext"

EFI_BOOT_CURRENT_VARIABLE_NAME  = "BootCurrent"

EFI_BOOT_OPTION_SUPPORT_VARIABLE_NAME  = "BootOptionSupport"

EFI_DRIVER_ORDER_VARIABLE_NAME  = "DriverOrder"

EFI_SYS_PREP_ORDER_VARIABLE_NAME  = "SysPrepOrder"

EFI_HW_ERR_REC_SUPPORT_VARIABLE_NAME  = "HwErrRecSupport"

EFI_SETUP_MODE_NAME  = "SetupMode"

EFI_KEY_EXCHANGE_KEY_NAME  = "KEK"

EFI_PLATFORM_KEY_NAME  = "PK"

EFI_SIGNATURE_SUPPORT_NAME  = "SignatureSupport"

EFI_SECURE_BOOT_MODE_NAME  = "SecureBoot"

EFI_KEK_DEFAULT_VARIABLE_NAME  = "KEKDefault"

EFI_PK_DEFAULT_VARIABLE_NAME  = "PKDefault"

EFI_DB_DEFAULT_VARIABLE_NAME  = "dbDefault"

EFI_DBX_DEFAULT_VARIABLE_NAME  = "dbxDefault"

EFI_DBT_DEFAULT_VARIABLE_NAME  = "dbtDefault"

EFI_OS_INDICATIONS_SUPPORT_VARIABLE_NAME  = "OsIndicationsSupported"

EFI_OS_INDICATIONS_VARIABLE_NAME  = "OsIndications"

EFI_VENDOR_KEYS_VARIABLE_NAME  = "VendorKeys"

